# Generated by Django 5.1.2 on 2024-12-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatstauts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatStauts',
        ),
    ]
