# Generated by Django 5.1.3 on 2024-12-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangers', '0001_initial'),
        ('skills', '0003_alter_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='skill_to_exchange',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
            preserve_default=False,
        ),
    ]
