# Generated by Django 5.1.3 on 2024-12-14 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangers', '0002_request_skill_to_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='scheduled_at',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='request',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
