# Generated by Django 5.1.3 on 2024-12-14 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangers', '0004_rename_scheduled_at_exchanger_end_date_and_more'),
        ('skills', '0003_alter_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanger',
            name='skills_exchanged',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchanger',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Ended', 'Ended')], default='Ongoing', max_length=10),
        ),
    ]
