# Generated by Django 5.1.3 on 2024-12-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangers', '0005_exchanger_skills_exchanged_exchanger_status'),
        ('skills', '0003_alter_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='skill_to_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
    ]
