# Generated by Django 5.1.3 on 2024-12-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangers', '0006_alter_request_skill_to_exchange'),
        ('skills', '0003_alter_skill_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchanger',
            name='skills_exchanged',
        ),
        migrations.AddField(
            model_name='exchanger',
            name='skills_exchanged',
            field=models.ManyToManyField(to='skills.skill'),
        ),
    ]
