# Generated by Django 5.1.3 on 2024-12-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangers', '0008_alter_exchanger_end_date_alter_exchanger_start_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchanger',
            unique_together=set(),
        ),
    ]
