# Generated by Django 5.1.3 on 2024-12-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_linkedin_url_profile_phone'),
        ('skills', '0003_alter_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_needed',
            field=models.ManyToManyField(related_name='skills_needed', to='skills.skill'),
        ),
    ]
