# Generated by Django 5.1.3 on 2024-12-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_subscribed',
        ),
    ]
