# Generated by Django 5.1.4 on 2024-12-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiries_type', models.CharField(blank=True, choices=[('General Questions', 'General Questions'), ('Technical Support', 'Technical Support'), ('Feedback or Suggestions', 'Feedback or Suggestions'), ('Account Issues', 'Account Issues'), ('Subscription and Payments', 'Subscription and Payments'), ('Skill Exchange Requests', 'Skill Exchange Requests'), ('Other', 'Other')], max_length=1024, null=True)),
            ],
        ),
    ]
