# Generated by Django 5.1.4 on 2024-12-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='inquiries_type',
            field=models.CharField(blank=True, choices=[('General Questions', 'General Questions'), ('Technical Support', 'Technical Support'), ('Feedback or Suggestions', 'Feedback or Suggestions'), ('Account Issues', 'Account Issues'), ('Subscription and Payments', 'Subscription and Payments'), ('Skill Exchange Requests', 'Skill Exchange Requests'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
