# Generated by Django 5.1.4 on 2024-12-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, choices=[('Free', 'Free'), ('Premium', 'Premium')], max_length=50, null=True)),
                ('plan_feture_1', models.TextField(blank=True, null=True)),
                ('plan_feture_2', models.TextField(blank=True, null=True)),
                ('plan_feture_3', models.TextField(blank=True, null=True)),
                ('plan_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(default='free', max_length=50),
        ),
    ]
