# Generated by Django 5.1.2 on 2024-12-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_plan_plan_amount_alter_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
